# Generated by Django 5.1.3 on 2024-11-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='dod',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='middleName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uology',
            field=models.TextField(blank=True, null=True),
        ),
    ]
