# Generated by Django 4.2.16 on 2024-11-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userdata', '0002_userdata_dob_userdata_dod_alter_userdata_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='dod',
            new_name='date_of_death',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='middleName',
            new_name='middle_name',
        ),
    ]
