# Generated by Django 4.2.16 on 2024-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdata', '0003_rename_dob_userdata_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
